-- 사용자 계정 생성 및 권한 설정
CREATE USER ITGOUPGO IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO ITGOUPGO;

-- 기존 테이블 삭제 구문 (FK 제약조건 문제 회피를 위해 역순 재정렬)
DROP TABLE INFO_BOOKMARK;
DROP TABLE INFO_FILE;
DROP TABLE INFO_REPLY;
DROP TABLE INFO_BBS;
DROP TABLE IT_BOOKMARK;
DROP TABLE IT_BBS;
DROP TABLE STUDY_REPLY;
DROP TABLE STUDY_BBS;
DROP TABLE KNOWLEDGE_FILE;
DROP TABLE KNOWLEDGE_LIKE;
DROP TABLE KNOWLEDGE_REPLY;
DROP TABLE KNOWLEDGE_BBS;
DROP TABLE FREE_DISLIKE;
DROP TABLE FREE_LIKE;
DROP TABLE FREE_REPLY;
DROP TABLE FREE_BBS;
DROP TABLE MESSAGE;
DROP TABLE AUTH;
DROP TABLE MEMBER;
DROP TABLE NOTICE;

-- 기존 시퀀스 삭제
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE MESSAGE_SEQ;
DROP SEQUENCE FREE_SEQ;
DROP SEQUENCE FREE_REPLY_SEQ;
DROP SEQUENCE KNOWLEDGE_SEQ;
DROP SEQUENCE KNOWLEDGE_REPLY_SEQ;
DROP SEQUENCE KNOWLEDGE_FILE_SEQ;
DROP SEQUENCE STUDY_SEQ;
DROP SEQUENCE STUDY_REPLY_SEQ;
DROP SEQUENCE IT_SEQ;
DROP SEQUENCE INFO_SEQ;
DROP SEQUENCE INFO_REPLY_SEQ;
DROP SEQUENCE INFO_FILE_SEQ;
DROP SEQUENCE NOTICE_SEQ;

-------------------------------------------------------
-- 1. 테이블 생성 구문 (오류 수정 및 논리적 개선 반영)
-------------------------------------------------------

-- MEMBER TABLE
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER CONSTRAINT MN_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) CONSTRAINT MID_NN NOT NULL
                           CONSTRAINT MID_UNQ UNIQUE,                           
    MEMBER_PWD VARCHAR2(100) CONSTRAINT MPWD_NN NOT NULL,
    MEMBER_NAME VARCHAR2(20) CONSTRAINT MNAME_NN NOT NULL,
    MEMBER_NICK VARCHAR2(24) CONSTRAINT MNICK_NN NOT NULL 
                             CONSTRAINT MNICK_UQ UNIQUE,
    MEMBER_BIRTH_DATE DATE,
    GENDER CHAR(1) CONSTRAINT GEN_CHK CHECK(GENDER IN ('M', 'F')) 
                   CONSTRAINT GEN_NN NOT NULL,
    EMAIL VARCHAR2(30) CONSTRAINT EMA_NN NOT NULL,
    PHONE VARCHAR2(13),
     -- *** 주소 관련 3개 컬럼 추가 시작 (2번 방식 적용) ***
    POSTCODE VARCHAR2(5) CONSTRAINT POSTCODE_NN NOT NULL,
    ADDR_MAIN VARCHAR2(100) CONSTRAINT ADDR_MAIN_NN NOT NULL,
    ADDR_DETAIL VARCHAR2(100), -- 상세 주소는 NULL 허용
    -- *** 주소 관련 3개 컬럼 추가 끝 ***
    ENROLL_DATE DATE DEFAULT SYSDATE CONSTRAINT EN_DATE_NN NOT NULL,
    MEMBER_STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT MSTA_CHK CHECK(MEMBER_STATUS IN ('Y', 'N'))
                          CONSTRAINT MSTA_NN NOT NULL
);

-- AUTH 테이블 (UNIQUE 제약조건 추가)
CREATE TABLE AUTH(
    EMAIL VARCHAR2(30) CONSTRAINT AU_EMA_NN NOT NULL CONSTRAINT AU_EMA_UNQ UNIQUE,
    AUTH_CODE NUMBER CONSTRAINT AC_NN NOT NULL,
    AUTH_DATE DATE DEFAULT SYSDATE CONSTRAINT AU_DATE_NN NOT NULL
);

-- 쪽지 테이블
CREATE TABLE MESSAGE(
    MSG_NO NUMBER CONSTRAINT MSG_PK PRIMARY KEY,
    MSG_TITLE VARCHAR2(100) CONSTRAINT MSG_TITLE_NN NOT NULL,
    MSG_CONTENT VARCHAR2(2000) CONSTRAINT MSG_CONTENT_NN NOT NULL,
    MSG_DATE DATE DEFAULT SYSDATE CONSTRAINT MSG_DATE_NN NOT NULL,
    MSG_READ_DATE DATE,
    MSG_DEL_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT MSG_STATUS_CHK CHECK (MSG_DEL_STATUS IN ('Y', 'N'))
                            CONSTRAINT MSG_STATUS_NN NOT NULL,
    SENDER NUMBER CONSTRAINT MSG_SENDER_NN NOT NULL,
    RECEIVER NUMBER CONSTRAINT MSG_RECEIVER_NN NOT NULL,
    CONSTRAINT MSG_SENDER_FK FOREIGN KEY (SENDER) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT MSG_RECEIVER_FK FOREIGN KEY (RECEIVER) REFERENCES MEMBER(MEMBER_NO)
);

-- 자유게시판 (FREE_VIEW DEFAULT 0 추가)
CREATE TABLE FREE_BBS(
    FREE_NO NUMBER CONSTRAINT FR_NO_PK PRIMARY KEY,
    FREE_TITLE VARCHAR2(100) CONSTRAINT FR_TITLE_NN NOT NULL,
    FREE_CONTENT VARCHAR2(4000) CONSTRAINT FR_CONTENT_NN NOT NULL,
    FREE_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT FR_CD_NN NOT NULL,
    FREE_VIEW NUMBER DEFAULT 0 CONSTRAINT FR_VIEW_NN NOT NULL,
    FREE_DELETE_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT FR_STATUS_CHK CHECK(FREE_DELETE_STATUS IN ('Y', 'N'))
                               CONSTRAINT FR_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT FREE_MN_NN NOT NULL,
    CONSTRAINT FREE_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

CREATE TABLE FREE_REPLY(
    FREE_REPLY_NO NUMBER CONSTRAINT FR_REPLY_PK PRIMARY KEY,
    FREE_REPLY_CONTENT VARCHAR2(1000) CONSTRAINT FR_REPLY_CONTENT_NN NOT NULL,
    FREE_REPLY_DELETE_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT FR_REPLY_STATUS_CHK CHECK (FREE_REPLY_DELETE_STATUS IN ('Y', 'N'))
                                                 CONSTRAINT FR_REPLY_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT FR_REPLY_MN_NN NOT NULL,
    FREE_NO NUMBER CONSTRAINT FR_REPLY_FN_NN NOT NULL,
    CONSTRAINT FR_REPLY_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FR_REPLY_FN_FK FOREIGN KEY (FREE_NO) REFERENCES FREE_BBS(FREE_NO)
);

-- FREE_LIKE (복합 Primary Key 추가)
CREATE TABLE FREE_LIKE(
    MEMBER_NO NUMBER CONSTRAINT FR_LIKE_MN_NN NOT NULL,
    FREE_NO NUMBER CONSTRAINT FR_LIKE_FN_NN NOT NULL,
    CONSTRAINT FR_LIKE_PK PRIMARY KEY (MEMBER_NO, FREE_NO),
    CONSTRAINT FR_LIKE_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FR_LIKE_FN_FK FOREIGN KEY (FREE_NO) REFERENCES FREE_BBS(FREE_NO)
);

-- FREE_DISLIKE (복합 Primary Key 추가)
CREATE TABLE FREE_DISLIKE(
    MEMBER_NO NUMBER CONSTRAINT FR_DLIKE_MN_NN NOT NULL,
    FREE_NO NUMBER CONSTRAINT FR_DLIKE_FN_NN NOT NULL,
    CONSTRAINT FR_DLIKE_PK PRIMARY KEY (MEMBER_NO, FREE_NO),
    CONSTRAINT FR_DLIKE_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FR_DLIKE_FN_FK FOREIGN KEY (FREE_NO) REFERENCES FREE_BBS(FREE_NO)
);

-- 지식인게시판 (KNOWLEDGE_VIEW DEFAULT 0 추가)
CREATE TABLE KNOWLEDGE_BBS(
    KNOWLEDGE_NO NUMBER CONSTRAINT KNOWLEDGE_PK PRIMARY KEY,
    KNOWLEDGE_TITLE VARCHAR2(100) CONSTRAINT KNOWLEDGE_TITLE_NN NOT NULL,
    KNOWLEDGE_CONTENT VARCHAR2(4000) CONSTRAINT KNOWLEDGE_CONTENT_NN NOT NULL,
    KNOWLEDGE_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT KNOWLEDGE_CREATE_DATE_NN NOT NULL,
    KNOWLEDGE_VIEW NUMBER DEFAULT 0 CONSTRAINT KNOWLEDGE_VIEW_NN NOT NULL,
    KNOWLEDGE_CATEGORY VARCHAR2(100) CONSTRAINT KNOWLEDGE_CATEGORY_NN NOT NULL,
    KNOWLEDGE_DELETE_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT KNOWLEDGE_DEL_STATUS_CHK CHECK (KNOWLEDGE_DELETE_STATUS IN ('Y', 'N'))
                                    CONSTRAINT KNOWLEDGE_DEL_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT KNOWLEDGE_MN_NN NOT NULL,
    CONSTRAINT KNOWLEDGE_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

CREATE TABLE KNOWLEDGE_REPLY(
    KNOWLEDGE_REPLY_NO NUMBER CONSTRAINT KNOWLEDGE_REPLY_PK PRIMARY KEY,
    KNOWLEDGE_REPLY_CONTENT VARCHAR2(1000) CONSTRAINT KNOWLEDGE_REPLY_CONTENT_NN NOT NULL,
    KNOWLEDGE_REPLY_DATE DATE DEFAULT SYSDATE CONSTRAINT KNOWLEDGE_REPLY_DATE_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT KNOWLEDGE_REPLY_MN_NN NOT NULL,
    KNOWLEDGE_NO NUMBER CONSTRAINT KNOWLEDGE_REPLY_KN_NN NOT NULL,
    CONSTRAINT KNOWLEDGE_REPLY_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT KNOWLEDGE_REPLY_KN_FK FOREIGN KEY (KNOWLEDGE_NO) REFERENCES KNOWLEDGE_BBS(KNOWLEDGE_NO)
);

-- KNOWLEDGE_LIKE (복합 Primary Key 추가)
CREATE TABLE KNOWLEDGE_LIKE(
    MEMBER_NO NUMBER CONSTRAINT KN_LIKE_MN_NN NOT NULL,
    KNOWLEDGE_NO NUMBER CONSTRAINT KN_LIKE_KN_NN NOT NULL,
    CONSTRAINT KN_LIKE_PK PRIMARY KEY (MEMBER_NO, KNOWLEDGE_NO),
    CONSTRAINT KN_LIKE_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT KN_LIKE_KN_FK FOREIGN KEY (KNOWLEDGE_NO) REFERENCES KNOWLEDGE_BBS(KNOWLEDGE_NO)
);

-- KNOWLEDGE_FILE (KNOWLEDGE_FILE_PATH 컬럼 추가)
CREATE TABLE KNOWLEDGE_FILE(
    KNOWLEDGE_FILE_NO NUMBER CONSTRAINT KN_FILE_PK PRIMARY KEY,
    KNOWLEDGE_FILE_ORIGIN_NAME VARCHAR2(100) CONSTRAINT KN_FILE_ORIGIN_NN NOT NULL,
    KNOWLEDGE_FILE_CHANGE_NAME VARCHAR2(100) CONSTRAINT KN_FILE_CHANGE_NN NOT NULL,
    KNOWLEDGE_FILE_PATH VARCHAR2(1000) CONSTRAINT KN_FILE_PATH_NN NOT NULL, -- 누락 컬럼 추가
    KNOWLEDGE_FILE_UPLOAD_DATE DATE DEFAULT SYSDATE CONSTRAINT KN_FILE_UPLOAD_DATE_NN NOT NULL,
    KNOWLEDGE_FILE_DELETE_STATUS CHAR(1) DEFAULT 'N'
    CONSTRAINT KN_FILE_DEL_STATUS_CHK CHECK (KNOWLEDGE_FILE_DELETE_STATUS IN ('Y', 'N'))
    CONSTRAINT KN_FILE_DEL_STATUS_NN NOT NULL,
    KNOWLEDGE_NO NUMBER CONSTRAINT KN_FILE_KN_NN NOT NULL,
    CONSTRAINT KN_FILE_KN_FK FOREIGN KEY (KNOWLEDGE_NO) REFERENCES KNOWLEDGE_BBS(KNOWLEDGE_NO)
);

-- 스터디게시판 (STUDY_VIEW DEFAULT 0 추가)
CREATE TABLE STUDY_BBS(
    STUDY_NO NUMBER CONSTRAINT STUDY_PK PRIMARY KEY,
    STUDY_TITLE VARCHAR2(100) CONSTRAINT STU_TITLE_NN NOT NULL,
    STUDY_CONTENT VARCHAR2(4000) CONSTRAINT STU_CONTENT_NN NOT NULL,
    STUDY_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT STU_CREATE_DATE_NN NOT NULL,
    STUDY_VIEW NUMBER DEFAULT 0 CONSTRAINT STU_VIEW_NN NOT NULL,
    STUDY_CATEGORY VARCHAR2(100) CONSTRAINT STU_CATEGORY_NN NOT NULL,
    STUDY_DELETE_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT STU_DEL_STATUS_CHK CHECK (STUDY_DELETE_STATUS IN ('Y', 'N'))
                                    CONSTRAINT STU_DEL_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT STU_MN_NN NOT NULL,
    CONSTRAINT STU_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

-- STUDY_REPLY (MEMBER_NO, STUDY_NO 컬럼 정의 추가)
CREATE TABLE STUDY_REPLY(
    STUDY_REPLY_NO NUMBER CONSTRAINT STU_REPLY_PK PRIMARY KEY,
    STUDY_REPLY_CONTENT VARCHAR2(1000) CONSTRAINT STU_REPLY_CONTENT_NN NOT NULL,
    STUDY_REPLY_DATE DATE DEFAULT SYSDATE CONSTRAINT STU_REPLY_DATE_NN NOT NULL,
    STUDY_REPLY_DELETE_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT STU_REPLY_DEL_STATUS_CHK CHECK (STUDY_REPLY_DELETE_STATUS IN ('Y', 'N'))
                                                  CONSTRAINT STU_REPLY_DEL_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT STU_REPLY_MN_NN NOT NULL, -- 누락 컬럼 추가
    STUDY_NO NUMBER CONSTRAINT STU_REPLY_SN_NN NOT NULL, -- 누락 컬럼 추가
    CONSTRAINT STU_REPLY_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    CONSTRAINT STU_REPLY_SN_FK FOREIGN KEY (STUDY_NO) REFERENCES STUDY_BBS (STUDY_NO)
);

-- IT 뉴스 게시판 (IT_VIEW DEFAULT 0 추가)
CREATE TABLE IT_BBS(
    IT_NO NUMBER CONSTRAINT IT_PK PRIMARY KEY,
    IT_TITLE VARCHAR2(100) CONSTRAINT IT_TITLE_NN NOT NULL,
    THUMBNAIL VARCHAR2(500),
    IT_CONTENT VARCHAR2(4000) CONSTRAINT IT_CONTENT_NN NOT NULL,
    REPORTER VARCHAR2(15) CONSTRAINT REPORTER_NN NOT NULL,
    NEWSPAPER VARCHAR2(30) CONSTRAINT NEWSPAPER_NN NOT NULL,
    IT_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT IT_CREATE_DATE_NN NOT NULL,
    IT_VIEW NUMBER DEFAULT 0 CONSTRAINT IT_VIEW_NN NOT NULL,
    IT_DELETE_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT IT_DEL_STATUS_CHK CHECK (IT_DELETE_STATUS IN ('Y', 'N'))
                                         CONSTRAINT IT_DEL_STATUS_NN NOT NULL
);

-- IT_BOOKMARK (복합 Primary Key 추가)
CREATE TABLE IT_BOOKMARK(
    IT_NO NUMBER CONSTRAINT IT_BOOKMARK_IN_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT IT_BOOKMARK_MN_NN NOT NULL,
    CONSTRAINT IT_BOOKMARK_PK PRIMARY KEY (IT_NO, MEMBER_NO),
    CONSTRAINT IT_BOOKMARK_IN_FK FOREIGN KEY (IT_NO) REFERENCES IT_BBS (IT_NO),
    CONSTRAINT IT_BOOKMARK_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

-- 정보나눔 게시판 (INFO_VIEW DEFAULT 0 추가)
CREATE TABLE INFO_BBS (
    INFO_NO NUMBER CONSTRAINT INFO_PK PRIMARY KEY,
    INFO_TITLE VARCHAR2(100) CONSTRAINT INFO_TITLE_NN NOT NULL,
    INFO_CONTENT VARCHAR2(4000) CONSTRAINT INFO_CONTENT_NN NOT NULL,
    INFO_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT INFO_CREATE_DATE_NN NOT NULL,
    INFO_VIEW NUMBER DEFAULT 0 CONSTRAINT INFO_VIEW_NN NOT NULL,
    INFO_CATEGORY VARCHAR2(40) CONSTRAINT INFO_CATEGORY_NN NOT NULL,
    INFO_DELETE_STATUS CHAR(1) DEFAULT 'N' 
        CONSTRAINT INFO_DEL_STATUS_CHK CHECK (INFO_DELETE_STATUS IN ('Y', 'N'))
        CONSTRAINT INFO_DEL_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT INFO_MN_NN NOT NULL,
    CONSTRAINT INFO_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

CREATE TABLE INFO_REPLY (
    INFO_REPLY_NO NUMBER CONSTRAINT INFO_REPLY_PK PRIMARY KEY,
    INFO_REPLY_CONTENT VARCHAR2(1000) CONSTRAINT INFO_REPLY_CONTENT_NN NOT NULL,
    INFO_REPLY_DATE DATE DEFAULT SYSDATE CONSTRAINT INFO_REPLY_DATE_NN NOT NULL,
    INFO_REPLY_DELETE_STATUS CHAR(1) DEFAULT 'N'
        CONSTRAINT INFO_REPLY_DEL_STATUS_CHK CHECK (INFO_REPLY_DELETE_STATUS IN ('Y', 'N'))
        CONSTRAINT INFO_REPLY_DEL_STATUS_NN NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT INFO_REPLY_MN_NN NOT NULL,
    INFO_NO NUMBER CONSTRAINT INFO_REPLY_IN_NN NOT NULL,
    CONSTRAINT INFO_REPLY_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT INFO_REPLY_IN_FK FOREIGN KEY (INFO_NO) REFERENCES INFO_BBS(INFO_NO)
);

CREATE TABLE INFO_FILE (
    INFO_FILE_NO NUMBER CONSTRAINT INFO_FILE_PK PRIMARY KEY,
    INFO_FILE_ORIGIN_NAME VARCHAR2(100) CONSTRAINT INFO_FILE_ORIGIN_NN NOT NULL,
    INFO_FILE_CHANGE_NAME VARCHAR2(100) CONSTRAINT INFO_FILE_CHANGE_NN NOT NULL,
    INFO_FILE_PATH VARCHAR2(1000) CONSTRAINT INFO_FILE_PATH_NN NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE CONSTRAINT INFO_FILE_UPLOAD_DATE_NN NOT NULL,
    INFO_FILE_DELETE_STATUS CHAR(1) DEFAULT 'N' 
        CONSTRAINT INFO_FILE_DEL_STATUS_CHK CHECK (INFO_FILE_DELETE_STATUS IN ('Y', 'N'))
        CONSTRAINT INFO_FILE_DEL_STATUS_NN NOT NULL,
    INFO_NO NUMBER CONSTRAINT INFO_FILE_IN_NN NOT NULL,
    CONSTRAINT INFO_FILE_IN_FK FOREIGN KEY (INFO_NO) REFERENCES INFO_BBS(INFO_NO)
);

-- INFO_BOOKMARK (복합 Primary Key 추가)
CREATE TABLE INFO_BOOKMARK (
    MEMBER_NO NUMBER CONSTRAINT INFO_BOOKMARK_MN_NN NOT NULL,
    INFO_NO NUMBER CONSTRAINT INFO_BOOKMARK_IN_NN NOT NULL,
    CONSTRAINT INFO_BOOKMARK_PK PRIMARY KEY (MEMBER_NO, INFO_NO),
    CONSTRAINT INFO_BOOKMARK_MN_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT INFO_BOOKMARK_IN_FK FOREIGN KEY (INFO_NO) REFERENCES INFO_BBS(INFO_NO)
);

-- 공지사항 게시판 (NOTICE_VIEW DEFAULT 0 추가)
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER CONSTRAINT NOTICE_PK PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) CONSTRAINT NOTICE_TITLE_NN NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL,
    NOTICE_CREATE_DATE DATE DEFAULT SYSDATE CONSTRAINT NOTICE_CREATE_DATE_NN NOT NULL,
    NOTICE_VIEW NUMBER DEFAULT 0 CONSTRAINT NOTICE_VIEW_NN NOT NULL,
    NOTICE_DELETE_STATUS CHAR(1) DEFAULT 'N' 
                         CONSTRAINT NOTICE_DEL_STATUS_CHK CHECK (NOTICE_DELETE_STATUS IN ('Y', 'N'))
                         CONSTRAINT NOTICE_DEL_STATUS_NN NOT NULL
);

-------------------------------------------------------
-- 2. COMMENT ON COLUMN 구문
-------------------------------------------------------

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEMBER_NICK IS '회원닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_BIRTH_DATE IS '회원생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '회원전화번호';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MEMBER_STATUS IS '회원탈퇴여부';

COMMENT ON COLUMN AUTH.EMAIL IS '인증이메일';
COMMENT ON COLUMN AUTH.AUTH_CODE IS '인증코드';
COMMENT ON COLUMN AUTH.AUTH_DATE IS '인증날짜';

COMMENT ON COLUMN MESSAGE.MSG_NO IS '쪽지 번호';
COMMENT ON COLUMN MESSAGE.MSG_TITLE IS '쪽지 제목';
COMMENT ON COLUMN MESSAGE.MSG_CONTENT IS '쪽지 내용';
COMMENT ON COLUMN MESSAGE.MSG_DATE IS '발신일';
COMMENT ON COLUMN MESSAGE.MSG_READ_DATE IS '쪽지 최초 열람 시간';
COMMENT ON COLUMN MESSAGE.MSG_DEL_STATUS IS '쪽지 삭제여부';
COMMENT ON COLUMN MESSAGE.SENDER IS '발신자';
COMMENT ON COLUMN MESSAGE.RECEIVER IS '수신자';

COMMENT ON COLUMN FREE_BBS.FREE_NO IS '자유게시판 글번호';
COMMENT ON COLUMN FREE_BBS.FREE_TITLE IS '자유게시판 제목';
COMMENT ON COLUMN FREE_BBS.FREE_CONTENT IS '자유게시판 내용';
COMMENT ON COLUMN FREE_BBS.FREE_CREATE_DATE IS '자유게시판 글 작성 날짜';
COMMENT ON COLUMN FREE_BBS.FREE_VIEW IS '자유게시판 조회수';
COMMENT ON COLUMN FREE_BBS.FREE_DELETE_STATUS IS '자유게시판 글 삭제여부';
COMMENT ON COLUMN FREE_BBS.MEMBER_NO IS '자유게시판 작성자';

COMMENT ON COLUMN FREE_REPLY.FREE_REPLY_NO IS '자유게시판 댓글 번호';
COMMENT ON COLUMN FREE_REPLY.FREE_REPLY_CONTENT IS '자유게시판 댓글 내용';
COMMENT ON COLUMN FREE_REPLY.FREE_REPLY_DELETE_STATUS IS '자유게시판 댓글 삭제여부';
COMMENT ON COLUMN FREE_REPLY.MEMBER_NO IS '자유게시판 댓글 등록한 회원번호';
COMMENT ON COLUMN FREE_REPLY.FREE_NO IS '자유게시판 댓글 단 게시글 번호';

COMMENT ON COLUMN FREE_LIKE.MEMBER_NO IS '자유게시판 좋아요 누른 회원번호';
COMMENT ON COLUMN FREE_LIKE.FREE_NO IS '자유게시판 좋아요 누른 게시글 번호';

COMMENT ON COLUMN FREE_DISLIKE.MEMBER_NO IS '자유게시판 싫어요 누른 회원번호';
COMMENT ON COLUMN FREE_DISLIKE.FREE_NO IS '자유게시판 싫어요 누른 게시글 번호';

COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_NO IS '지식인게시판 글 번호';
COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_TITLE IS '지식인게시판 글 제목';
COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_CONTENT IS '지식인게시판 글 내용';
COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_CREATE_DATE IS '지식인게시판 글 작성일';
COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_VIEW IS '지식인게시판 글 조회수';
COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_CATEGORY IS '지식인게시판 카테고리';
COMMENT ON COLUMN KNOWLEDGE_BBS.KNOWLEDGE_DELETE_STATUS IS '지식인게시판 글 삭제여부';
COMMENT ON COLUMN KNOWLEDGE_BBS.MEMBER_NO IS '지식인게시판 글 작성자';

COMMENT ON COLUMN KNOWLEDGE_REPLY.KNOWLEDGE_REPLY_NO IS '지식인게시판 댓글 번호';
COMMENT ON COLUMN KNOWLEDGE_REPLY.KNOWLEDGE_REPLY_CONTENT IS '지식인게시판 댓글 내용';
COMMENT ON COLUMN KNOWLEDGE_REPLY.KNOWLEDGE_REPLY_DATE IS '지식인게시판 댓글 작성일';
COMMENT ON COLUMN KNOWLEDGE_REPLY.MEMBER_NO IS '지식인게시판 댓글 작성자';
COMMENT ON COLUMN KNOWLEDGE_REPLY.KNOWLEDGE_NO IS '지식인게시판 댓글 단 게시글 번호';

COMMENT ON COLUMN KNOWLEDGE_LIKE.MEMBER_NO IS '지식인게시판 좋아요 누른 회원번호';
COMMENT ON COLUMN KNOWLEDGE_LIKE.KNOWLEDGE_NO IS '지식인게시판 좋아요 누른 게시글 번호';

COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_FILE_NO IS '지식인게시판 파일 번호';
COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_FILE_ORIGIN_NAME IS '지식인게시판 파일 원본파일명';
COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_FILE_CHANGE_NAME IS '지식인게시판 파일 수정파일명';
COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_FILE_PATH IS '지식인게시판 파일 저장경로';
COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_FILE_UPLOAD_DATE IS '지식인게시판 파일 업로드일';
COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_FILE_DELETE_STATUS IS '지식인게시판 파일 삭제여부';
COMMENT ON COLUMN KNOWLEDGE_FILE.KNOWLEDGE_NO IS '지식인게시판 파일이 속한 글 번호';

COMMENT ON COLUMN STUDY_BBS.STUDY_NO IS '스터디게시판 글 번호';
COMMENT ON COLUMN STUDY_BBS.STUDY_TITLE IS '스터디게시판 글 제목';
COMMENT ON COLUMN STUDY_BBS.STUDY_CONTENT IS '스터디게시판 글 내용';
COMMENT ON COLUMN STUDY_BBS.STUDY_CREATE_DATE IS '스터디게시판 글 작성일';
COMMENT ON COLUMN STUDY_BBS.STUDY_VIEW IS '스터디게시판 글 조회수';
COMMENT ON COLUMN STUDY_BBS.STUDY_CATEGORY IS '스터디게시판 글 카테고리';
COMMENT ON COLUMN STUDY_BBS.STUDY_DELETE_STATUS IS '스터디게시판 글 삭제여부';
COMMENT ON COLUMN STUDY_BBS.MEMBER_NO IS '스터디게시판 글 작성자';

COMMENT ON COLUMN STUDY_REPLY.STUDY_REPLY_NO IS '스터디게시판 댓글 번호';
COMMENT ON COLUMN STUDY_REPLY.STUDY_REPLY_CONTENT IS '스터디게시판 댓글 내용';
COMMENT ON COLUMN STUDY_REPLY.STUDY_REPLY_DATE IS '스터디게시판 댓글 작성일';
COMMENT ON COLUMN STUDY_REPLY.STUDY_REPLY_DELETE_STATUS IS '스터디게시판 댓글 삭제여부';
COMMENT ON COLUMN STUDY_REPLY.MEMBER_NO IS '스터디게시판 댓글 작성자';
COMMENT ON COLUMN STUDY_REPLY.STUDY_NO IS '스터디게시판 댓글 단 글 번호';

COMMENT ON COLUMN IT_BBS.IT_NO IS 'IT 뉴스 게시판 글 번호';
COMMENT ON COLUMN IT_BBS.IT_TITLE IS 'IT 뉴스 게시판 글 제목';
COMMENT ON COLUMN IT_BBS.THUMBNAIL IS 'IT 뉴스 게시판 글 썸네일 이미지 경로';
COMMENT ON COLUMN IT_BBS.IT_CONTENT IS 'IT 뉴스 게시판 글 내용';
COMMENT ON COLUMN IT_BBS.REPORTER IS 'IT 뉴스 게시판 기자 이름';
COMMENT ON COLUMN IT_BBS.NEWSPAPER IS 'IT 뉴스 게시판 신문사';
COMMENT ON COLUMN IT_BBS.IT_CREATE_DATE IS 'IT 뉴스 게시판 글 작성일';
COMMENT ON COLUMN IT_BBS.IT_VIEW IS 'IT 뉴스 게시판 글 조회수';
COMMENT ON COLUMN IT_BBS.IT_DELETE_STATUS IS 'IT 뉴스 게시판 글 삭제여부';

COMMENT ON COLUMN IT_BOOKMARK.IT_NO IS 'IT 게시판 북마크 한 글 번호';
COMMENT ON COLUMN IT_BOOKMARK.MEMBER_NO IS 'IT 게시판 북마크 한 회원 번호';

COMMENT ON COLUMN INFO_BBS.INFO_NO IS '정보나눔 게시글 번호';
COMMENT ON COLUMN INFO_BBS.INFO_TITLE IS '정보나눔 게시글 제목';
COMMENT ON COLUMN INFO_BBS.INFO_CONTENT IS '정보나눔 게시글 내용';
COMMENT ON COLUMN INFO_BBS.INFO_CREATE_DATE IS '정보나눔 게시글 작성일';
COMMENT ON COLUMN INFO_BBS.INFO_VIEW IS '정보나눔 게시글 조회수';
COMMENT ON COLUMN INFO_BBS.INFO_CATEGORY IS '정보나눔 게시글 카테고리';
COMMENT ON COLUMN INFO_BBS.INFO_DELETE_STATUS IS '정보나눔 게시글 삭제여부';
COMMENT ON COLUMN INFO_BBS.MEMBER_NO IS '정보나눔 게시글 작성자';

COMMENT ON COLUMN INFO_REPLY.INFO_REPLY_NO IS '정보나눔 댓글 번호';
COMMENT ON COLUMN INFO_REPLY.INFO_REPLY_CONTENT IS '정보나눔 댓글 내용';
COMMENT ON COLUMN INFO_REPLY.INFO_REPLY_DATE IS '정보나눔 댓글 작성일';
COMMENT ON COLUMN INFO_REPLY.INFO_REPLY_DELETE_STATUS IS '정보나눔 댓글 삭제여부';
COMMENT ON COLUMN INFO_REPLY.MEMBER_NO IS '정보나눔 댓글 작성자';
COMMENT ON COLUMN INFO_REPLY.INFO_NO IS '댓글이 달린 정보나눔 글 번호';

COMMENT ON COLUMN INFO_FILE.INFO_FILE_NO IS '정보나눔 첨부파일 번호';
COMMENT ON COLUMN INFO_FILE.INFO_FILE_ORIGIN_NAME IS '정보나눔 첨부파일 원본명';
COMMENT ON COLUMN INFO_FILE.INFO_FILE_CHANGE_NAME IS '정보나눔 첨부파일 수정명';
COMMENT ON COLUMN INFO_FILE.INFO_FILE_PATH IS '정보나눔 첨부파일 저장경로';
COMMENT ON COLUMN INFO_FILE.UPLOAD_DATE IS '정보나눔 첨부파일 업로드일';
COMMENT ON COLUMN INFO_FILE.INFO_FILE_DELETE_STATUS IS '정보나눔 첨부파일 삭제여부';
COMMENT ON COLUMN INFO_FILE.INFO_NO IS '정보나눔 첨부파일이 속한 글 번호';

COMMENT ON COLUMN INFO_BOOKMARK.MEMBER_NO IS '정보나눔 게시글 북마크한 회원번호';
COMMENT ON COLUMN INFO_BOOKMARK.INFO_NO IS '정보나눔 게시글 북마크된 글 번호';

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 글 번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항 글 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항 글 내용';
COMMENT ON COLUMN NOTICE.NOTICE_CREATE_DATE IS '공지사항 글 작성일';
COMMENT ON COLUMN NOTICE.NOTICE_VIEW IS '공지사항 글 조회수';
COMMENT ON COLUMN NOTICE.NOTICE_DELETE_STATUS IS '공지사항 글 삭제여부';

-------------------------------------------------------
-- 3. SEQUENCE (자동 번호 생성기)
-------------------------------------------------------

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE FREE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE FREE_REPLY_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE KNOWLEDGE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE KNOWLEDGE_REPLY_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE KNOWLEDGE_FILE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE STUDY_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE STUDY_REPLY_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE IT_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE INFO_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE INFO_REPLY_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE INFO_FILE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE NOTICE_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;